apiVersion: v1 
kind: Service 
metadata:
  name: {{.Values.deployment.app1.service.name}}
spec:
  selector:
    app: {{.Values.deployment.app1.labels.app}}
  type: {{.Values.deployment.app1.service.type}}
  ports:
    - name: http
      port: 80
      targetPort: {{.Values.deployment.app1.containerport}}  
